// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremiumAccountService.Infrastructure.Context;

#nullable disable

namespace PremiumAccountService.Infrastructure.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20240913201459_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PremiumAccountService.Domain.Entities.Coverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PremiumRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("coverages");
                });

            modelBuilder.Entity("PremiumAccountService.Domain.Entities.InsuranceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InsuranceRequests");
                });

            modelBuilder.Entity("PremiumAccountService.Domain.Entities.InsuranceRequestCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoverageId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("PayementAmount")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.HasIndex("InsuranceRequestId");

                    b.ToTable("InsuranceRequestCoverages");
                });

            modelBuilder.Entity("PremiumAccountService.Domain.Entities.InsuranceRequestCoverage", b =>
                {
                    b.HasOne("PremiumAccountService.Domain.Entities.Coverage", "Coverage")
                        .WithMany()
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PremiumAccountService.Domain.Entities.InsuranceRequest", "InsuranceRequest")
                        .WithMany("RequestCoverages")
                        .HasForeignKey("InsuranceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coverage");

                    b.Navigation("InsuranceRequest");
                });

            modelBuilder.Entity("PremiumAccountService.Domain.Entities.InsuranceRequest", b =>
                {
                    b.Navigation("RequestCoverages");
                });
#pragma warning restore 612, 618
        }
    }
}
